### PR TITLE
fixed to_euler function in quat.py

### PR DESCRIPTION
**Pull request by kai-lan**
I have tested with all six orderings against `scipy.spatial.transform.Rotation`, and all showed the correct results.

### CODE REVIEW

**Comment by orangeduck** [comment]
Thanks Kai this looks great. I will check it and merge it soon.

**Comment by orangeduck** [comment]
Does this change the behavior for `bvh.save`? In which case does this function call and the following one need updating?

https://github.com/orangeduck/Motion-Matching/blob/main/resources/train_decompressor.py#L325

**Comment by kai-lan** [comment]
Yes, you need to include the correct order to `quat.to_euler(..)` function.
In line 326, it should be 
```
'rotations': np.degrees(quat.to_euler(Ygnd_rot[0].cpu().numpy(), order='zyx' )),
```
and in line 335,
```
'rotations': np.degrees(quat.to_euler(Ytil_rot, order='zyx')),
```

**Comment by orangeduck** [comment]
Okay I've submitted a fix for that in [37df18a](https://github.com/orangeduck/Motion-Matching/commit/37df18afc44e8acca3af5e85dff96effa6a34b03)

**Pull request merged**
